--CREATING MAIN TASK
CREATE TABLE Student (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  faculty_number INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  surname VARCHAR(255) NOT NULL
);

INSERT INTO Student VALUES(NULL,	9706243, 'Teodor', 'Hristov');

DELETE FROM Student WHERE ID=1 OR NAME='Teodor';

SELECT * FROM Student;

/*END_OF_THE_MAIN_TASK*/
/*BONUS_TASK_1*/
CREATE TABLE Student (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  faculty_number INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  surname VARCHAR(255) NOT NULL,
  course_id INT NOT NULL
);

CREATE TABLE Course (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  credits INT NOT NULL
);

INSERT INTO Course VALUES(NULL, 'Artificial Intelligence', 'intelligence demonstrated by machines.', 500);
INSERT INTO Student VALUES(NULL,	9706243, 'Teodor', 'Hristov', 3);

/*REMOVING BY WORD*/
DELETE FROM Course WHERE description LIKE '%intelligence%';

SELECT* FROM Course;
SELECT S.ID,S.NAME,C.NAME,C.DESCRIPTION FROM Student AS S JOIN Course AS C ON S.COURSE_ID=C.ID;

/*END_OF_BONUS_1*/
/*BONUS_TASK_2*/
CREATE TABLE Student (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  faculty_id INT NOT NULL,
  faculty_number INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  surname VARCHAR(255) NOT NULL
);

CREATE TABLE Faculty (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL
);
INSERT INTO Faculty VALUES(NULL, 'SOFIA UNIVERSITY');
INSERT INTO Faculty VALUES(NULL, 'MIT');
INSERT INTO Faculty VALUES(NULL, 'VUZF');

SELECT * FROM Faculty;

INSERT INTO Student VALUES(NULL, 1,1123456,'TEODOR', 'HRISTOV');
INSERT INTO Student VALUES(NULL, 2,1231243554,'ALBERT', 'IVANOV');
INSERT INTO Student VALUES(NULL, 1,454525345,'QSEN', 'HRISTOV');
INSERT INTO Student VALUES(NULL, 2,345435,'PESHO', 'HRISTOV');
SELECT * FROM Student;

--DELETING Student
DELETE S FROM Student S WHERE S.ID=5;

--DELETING Faculty
DELETE F FROM Faculty F WHERE F.NAME='VUZF';

/*GETTING ALL UNIVERSITIES & THEIR STUDENTS*/
SELECT S.ID,S.FACULTY_NUMBER,S.NAME,S.SURNAME,F.NAME FROM Student AS S JOIN Faculty AS F ON S.FACULTY_ID=F.ID;

/*GETTING ALL STUDENTS FROM UNIVERSITY WHERE UNIVERSITY.NAME CONTAINS SPECIFIC WORD IN THIS CASE SOFIA*/
SELECT S.ID,S.FACULTY_NUMBER,S.NAME,S.SURNAME,F.NAME FROM Student AS S JOIN Faculty AS F ON S.FACULTY_ID=F.ID WHERE F.NAME LIKE '%SOFIA%';
/*END OF BONUS_TASK_2*/

-- START OF BONUS_TASK_3
DELETE F,S FROM Faculty F JOIN Student S WHERE F.NAME='MIT' AND S.FACULTY_ID=F.ID;
